import React, { useState, useEffect } from 'react';
import { Scissors, CalendarDays, Clock, User, Phone, ChevronRight, ArrowLeft, CheckCircle2, Star, MapPin, Instagram, Lock, LogOut, CalendarRange, RotateCcw, WifiOff } from "lucide-react";
// O restante do seu código App.jsx continua exatamente igual aqui...
